name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black build

      - name: Lint with flake8
        run: |
          flake8 sketchlib --max-line-length=88

      - name: Check formatting with black
        run: |
          black --check sketchlib

      - name: Run tests
        run: |
          pytest tests/

      - name: Build package
        if: github.event_name == 'release'
        run: |
          python -m build

      - name: Publish to PyPI
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          twine upload dist/*
